import './models/player.dart';

import './models/team.dart';
import 'package:flutter/material.dart';

const Teams = const [
  Team(
    id: "t1",
    imgUrl: "assets/images/ipl_teams/csk.png",
    abbrv: "CSK",
    name: "Chennai Super Kings ",
    jerseyColor: Color.fromRGBO(224, 173, 2, 1),
  ),
  Team(
      imgUrl: "assets/images/ipl_teams/mi.png",
      id: "t2",
      abbrv: "MI",
      name: "Mumbai Indians",
      jerseyColor: Color.fromRGBO(0, 106, 195, 1)),
  Team(
      id: "t5",
      abbrv: "RCB",
      name: "Royal Challengers Bangalore",
      imgUrl: "assets/images/ipl_teams/rcb.png",
      jerseyColor: Color.fromRGBO(230, 12, 0, 1)),
  Team(
      id: "t6",
      abbrv: "SRH",
      name: "Sunrisers Hyderabad",
      imgUrl: "assets/images/ipl_teams/srh.png",
      jerseyColor: Color.fromRGBO(255, 124, 0, 1)),
  Team(
      id: "t4",
      abbrv: "DC",
      name: "Delhi Capitals",
      imgUrl: "assets/images/ipl_teams/dc.png",
      jerseyColor: Color.fromRGBO(14, 43, 120, 1)),
  Team(
      imgUrl: "assets/images/ipl_teams/rr.png",
      id: "t8",
      abbrv: "RR",
      name: "Rajasthan Royals",
      jerseyColor: Color.fromRGBO(238, 130, 238, 1)),
  Team(
      id: "t7",
      abbrv: "PBKS",
      name: "Punjab Kings",
      imgUrl: "assets/images/ipl_teams/pk.png",
      jerseyColor: Color.fromRGBO(255, 0, 0, 1)),
  Team(
    imgUrl: "assets/images/ipl_teams/kkr.png",
    id: "t3",
    abbrv: "KKR",
    name: "Kolkata Knight Riders",
    jerseyColor: Color.fromRGBO(74, 68, 126, 1),
  ),
];

// All players
/*
id
name
buy-price
country
role
img
stats
*/

const Players = [
  Player(
    id: "p1",
    name: "Virat Kohli",
    role: "Batsman",
    price: "20cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/vk.png",
    jerseyNo: 18,
    iplStats: {
      "Matches": 212,
      "Runs": 5040,
      "Avg": 44.44,
      "Best-Score": 122,
    },
    countryName: "IND",
    teamId: "t5",
  ),
  Player(
    id: "p2",
    name: "AB deviliers",
    role: "Batsman",
    price: "25cr",
    country: "assets/images/country_flags/sa.png",
    profileImg: "assets/images/players/abd.png",
    jerseyNo: 17,
    countryName: "SA",
    iplStats: {
      "Matches": 192,
      "Runs": 4040,
      "Avg": 45.44,
      "Best-Score": 142,
    },
    teamId: "t5",
  ),
  Player(
    id: "p3",
    name: "Yuzvendra Chahal",
    role: "Bowler",
    price: "12cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/chahal.png",
    jerseyNo: 3,
    iplStats: {
      "Matches": 83,
      "Wickets": 100,
      "Economy": 8.24,
      "Best-Figures": "4/33",
    },
    teamId: "t5",
    countryName: "IND",
  ),
  Player(
    id: "p4",
    name: "Rohit Sharma",
    role: "Batsman",
    countryName: "IND",
    price: "22cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/rohit.png",
    jerseyNo: 45,
    iplStats: {
      "Matches": 123,
      "Runs": 4033,
      "Avg": 41.22,
      "Best-Score": 122,
    },
    teamId: "t2",
  ),
  Player(
    id: "p5",
    name: "Jasprit Bumrah",
    role: "Bowler",
    price: "17cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/bumrah.png",
    jerseyNo: 93,
    countryName: "IND",
    iplStats: {
      "Matches": 57,
      "Wickets": 92,
      "Economy": 7.24,
      "Best-Figures": "5/23",
    },
    teamId: "t2",
  ),
  Player(
    id: "p6",
    name: "Kieron Pollard",
    role: "All-Rounder",
    price: "22cr",
    country: "assets/images/country_flags/wi.png",
    profileImg: "assets/images/players/polly.png",
    jerseyNo: 55,
    countryName: "WI",
    iplStats: {
      "Matches": 199,
      "Wickets": 73,
      "Runs": 3382,
      "Economy": 7.24,
      "Avg": 39.33,
      "Best-Figures": "3/23",
      "Best-Score": "99",
    },
    teamId: "t2",
  ),
  Player(
    id: "p7",
    name: "Faf duplesis",
    role: "Batsman",
    price: "18cr",
    country: "assets/images/country_flags/sa.png",
    profileImg: "assets/images/players/faf.png",
    jerseyNo: 13,
    countryName: "SA",
    iplStats: {
      "Matches": 122,
      "Runs": 4040,
      "Avg": 41.44,
      "Best-Score": 112,
    },
    teamId: "t1",
  ),
  Player(
    id: "p8",
    name: "Ravindra Jadeja",
    role: "All-Rounder",
    price: "19cr",
    countryName: "IND",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/jaddu.png",
    jerseyNo: 8,
    iplStats: {
      "Matches": 133,
      "Wickets": 102,
      "Runs": 2334,
      "Economy": 9.24,
      "Avg": 33.33,
      "Best-Figures": "5/13",
      "Best-Score": "78",
    },
    teamId: "t1",
  ),
  Player(
    id: "p9",
    name: "Sam Curran",
    role: "Bowler",
    price: "13cr",
    country: "assets/images/country_flags/eng.png",
    profileImg: "assets/images/players/sam.png",
    jerseyNo: 58,
    countryName: "ENG",
    iplStats: {
      "Matches": 54,
      "Wickets": 69,
      "Economy": 8.34,
      "Best-Figures": "4/33",
    },
    teamId: "t1",
  ),
  Player(
    id: "p10",
    name: "Shubhman Gill",
    role: "Batsman",
    price: "8cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/gill.png",
    jerseyNo: 99,
    countryName: "IND",
    iplStats: {
      "Matches": 34,
      "Runs": 1022,
      "Avg": 33.22,
      "Best-Score": "87",
    },
    teamId: "t3",
  ),
  Player(
    id: "p11",
    name: "Pat Cummins",
    role: "Bowler",
    price: "15cr",
    country: "assets/images/country_flags/aus.png",
    profileImg: "assets/images/players/pat.png",
    jerseyNo: 63,
    countryName: "ENG",
    iplStats: {
      "Matches": 77,
      "Wickets": 85,
      "Economy": 8.54,
      "Best-Figures": "5/22",
    },
    teamId: "t3",
  ),
  Player(
    id: "p12",
    name: "Andre Russle",
    role: "All-Rounder",
    price: "22cr",
    countryName: "WI",
    country: "assets/images/country_flags/wi.png",
    profileImg: "assets/images/players/russle.png",
    jerseyNo: 12,
    iplStats: {
      "Matches": 97,
      "Wickets": 78,
      "Runs": 3433,
      "Economy": 9.24,
      "Avg": 39.33,
      "Best-Figures": "3/23",
      "Best-Score": "102",
    },
    teamId: "t3",
  ),
  Player(
    id: "p14",
    name: "Kane Willamson",
    role: "Batsman",
    price: "18cr",
    country: "assets/images/country_flags/nz.png",
    profileImg: "assets/images/players/kane.png",
    jerseyNo: 22,
    countryName: "NZ",
    iplStats: {
      "Matches": 110,
      "Runs": 4022,
      "Avg": 44.22,
      "Best-Score": "112",
    },
    teamId: "t6",
  ),
  Player(
    id: "p15",
    name: "Rashid Khan",
    role: "Bowler",
    price: "13cr",
    country: "assets/images/country_flags/af.png",
    profileImg: "assets/images/players/rashid.png",
    jerseyNo: 19,
    countryName: "AF",
    iplStats: {
      "Matches": 87,
      "Wickets": 123,
      "Economy": 7.99,
      "Best-Figures": "4/12",
    },
    teamId: "t6",
  ),
  Player(
    id: "p13",
    name: "Jason Holder",
    role: "All-Rounder",
    price: "10cr",
    country: "assets/images/country_flags/wi.png",
    profileImg: "assets/images/players/holder.png",
    jerseyNo: 98,
    countryName: "WI",
    iplStats: {
      "Matches": 66,
      "Runs": 728,
      "Avg": 22.33,
      "Wickets": 79,
      "Economy": 9.44,
      "Best-Score": "44",
      "Best-Figures": "4/32",
    },
    teamId: "t6",
  ),
  Player(
    id: "p16",
    name: "Rishab Pant",
    role: "Batsman",
    price: "14cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/pant.png",
    jerseyNo: 17,
    countryName: "IND",
    iplStats: {
      "Matches": 89,
      "Runs": 3082,
      "Avg": 42.22,
      "Best-Score": "107",
    },
    teamId: "t4",
  ),
  Player(
    id: "p17",
    name: "Kagiso Rabada",
    role: "Bowler",
    price: "20cr",
    country: "assets/images/country_flags/sa.png",
    profileImg: "assets/images/players/rabada.png",
    jerseyNo: 58,
    countryName: "SA",
    iplStats: {
      "Matches": 103,
      "Wickets": 133,
      "Economy": 8.19,
      "Best-Figures": "5/21",
    },
    teamId: "t4",
  ),
  Player(
    id: "p18",
    name: "Marcus Stoinis",
    role: "All-Rounder",
    price: "11cr",
    country: "assets/images/country_flags/aus.png",
    profileImg: "assets/images/players/stoinis.png",
    jerseyNo: 21,
    countryName: "AUS",
    iplStats: {
      "Matches": 78,
      "Runs": 1233,
      "Avg": 33.13,
      "Wickets": 49,
      "Economy": 10.44,
      "Best-Score": "75",
      "Best-Figures": "3/22",
    },
    teamId: "t4",
  ),
  Player(
    id: "p19",
    name: "Jos Buttler",
    role: "Batsman",
    price: "17cr",
    country: "assets/images/country_flags/eng.png",
    profileImg: "assets/images/players/buttler.png",
    jerseyNo: 63,
    countryName: "ENG",
    iplStats: {
      "Matches": 109,
      "Runs": 3462,
      "Avg": 40.42,
      "Best-Score": "109",
    },
    teamId: "t8",
  ),
  Player(
    id: "p20",
    name: "Shreyas Gopal",
    role: "Bowler",
    price: "7cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/gopal.png",
    jerseyNo: 23,
    countryName: "IND",
    iplStats: {
      "Matches": 78,
      "Wickets": 102,
      "Economy": 8.49,
      "Best-Figures": "4/18",
    },
    teamId: "t8",
  ),
  Player(
    id: "p21",
    name: "Ben Stokes",
    role: "All-Rounder",
    price: "22cr",
    country: "assets/images/country_flags/eng.png",
    profileImg: "assets/images/players/stokes.png",
    jerseyNo: 55,
    countryName: "ENG",
    iplStats: {
      "Matches": 121,
      "Runs": 3473,
      "Avg": 39.13,
      "Wickets": 67,
      "Economy": 9.54,
      "Best-Score": "107",
      "Best-Figures": "3/22",
    },
    teamId: "t8",
  ),
  Player(
    id: "p22",
    name: "KL Rahul",
    role: "Batsman",
    price: "19cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/kl.png",
    jerseyNo: 01,
    countryName: "IND",
    iplStats: {
      "Matches": 122,
      "Runs": 4433,
      "Avg": 41.82,
      "Best-Score": "129",
    },
    teamId: "t7",
  ),
  Player(
    id: "p23",
    name: "David Malan",
    role: "Batsman",
    price: "13cr",
    country: "assets/images/country_flags/eng.png",
    profileImg: "assets/images/players/malan.png",
    jerseyNo: 35,
    countryName: "ENG",
    iplStats: {
      "Matches": 2,
      "Runs": 83,
      "Avg": 41.33,
      "Best-Score": "55",
    },
    teamId: "t7",
  ),
  Player(
    id: "p24",
    name: "Mohamamad Shami",
    role: "Bowler",
    price: "14cr",
    country: "assets/images/country_flags/ind.png",
    profileImg: "assets/images/players/shami.png",
    jerseyNo: 11,
    countryName: "IND",
    iplStats: {
      "Matches": 98,
      "Wickets": 111,
      "Economy": 9.39,
      "Best-Figures": "5/22",
    },
    teamId: "t7",
  ),
];
